/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BAL.TimeBAL;
import VO.TimeVO;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.channels.FileChannel;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author abol9
 */
public class UiEdit extends javax.swing.JFrame {

    MaskFormatter formatoDate;
    int id;
    String oldName;
    UiPrincipal framePai;

    /**
     * Creates new form UiEdit
     */
    public UiEdit(UiPrincipal framePai) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.framePai=framePai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lbEscudo = new javax.swing.JLabel();
        lbFundacao = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbPatrimonio = new javax.swing.JLabel();
        txtEscudo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtPatrimonio = new javax.swing.JTextField();
        try{ formatoDate = new MaskFormatter("##/##/####");  } catch(Exception e){ JOptionPane.showMessageDialog(null, "Não é possível usar o formatador"); }
        txtFormattedFundacao = new JFormattedTextField(formatoDate);
        btnProcurarImg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBack.setText("Voltar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbEscudo.setText("Escudo");

        lbFundacao.setText("Data de Fundação");

        lbNome.setText("Nome");

        lbPatrimonio.setText("Patrimonio");

        btnProcurarImg.setText("Procurar");
        btnProcurarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                        .addComponent(btnEdit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPatrimonio)
                            .addComponent(lbNome)
                            .addComponent(lbFundacao)
                            .addComponent(lbEscudo))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(txtEscudo, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(txtPatrimonio, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(txtFormattedFundacao))
                        .addGap(18, 18, 18)
                        .addComponent(btnProcurarImg)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFundacao)
                    .addComponent(txtFormattedFundacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEscudo)
                    .addComponent(txtEscudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurarImg))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPatrimonio)
                    .addComponent(txtPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnBack))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        TimeBAL timeBAL = new TimeBAL();

        String escudo = txtEscudo.getText();
        Date fund = Date.valueOf("0001-01-01");
        try {
            fund = timeBAL.VerificarData(txtFormattedFundacao.getText());
        } catch (Exception ex) {
            //exceção ja lançada
            return;
        }

        String nome = txtNome.getText();
        editarNomeImg();
        
        BigDecimal patrimonio = BigDecimal.ZERO;
        try {
            patrimonio = new BigDecimal(txtPatrimonio.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Valor do patrimonio incorreto, por favor tente novamente");
            return;
        }

        TimeVO time = new TimeVO(escudo, fund, nome, patrimonio);

        try {
            timeBAL.Edit(time, id);
        } catch (SQLException ex) {
            //exceção ja lançada
            return;
        }
        
        try {
            framePai.Carregar();
        } catch (SQLException ex) {
            Logger.getLogger(UiInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Cadastro editado com sucesso");
        this.setVisible(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //limpar
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnProcurarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarImgActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);

        File f = chooser.getSelectedFile();

        String filename = f.getAbsolutePath();
        txtEscudo.setText(filename);
        File copia = new File("src/imagens/" + txtNome.getText() + ".jpg");
        if (!copia.exists()) {
            try {
                copiar(f, copia);
            } catch (IOException ex) {
                Logger.getLogger(UiInsert.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnProcurarImgActionPerformed
                                      
    public void copiar(File fonte, File destino) throws FileNotFoundException, IOException {
        FileChannel in = new FileInputStream(fonte).getChannel();
        FileChannel out = new FileOutputStream(destino).getChannel();
        out.transferFrom(in, 0, in.size());

        in.close();
        out.close();
    }
    
    public void editarNomeImg()
    {
        File f = new File("src/imagens/" + oldName + ".jpg");
        File copia = new File("src/imagens/" + txtNome.getText() + ".jpg");
        if (!copia.exists()) {
            try {
                copiar(f, copia);
            }catch (IOException ex) {
                Logger.getLogger(UiInsert.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void DeixarVisivel(TimeVO time) throws ParseException {
        this.setVisible(true);

        txtEscudo.setText(time.getEscudo());
        //txtFormattedFundacao.setText(time.getFundacao().toString());
        //1997-09-21
        //21091997
        String datecorretc = time.getFundacao().toString();
        datecorretc=datecorretc.replace("-", "");
        String reverse = "";
        reverse += datecorretc.charAt(6);
        reverse += datecorretc.charAt(7);

        reverse += datecorretc.charAt(4);
        reverse += datecorretc.charAt(5);

        reverse += datecorretc.charAt(0);
        reverse += datecorretc.charAt(1);
        reverse += datecorretc.charAt(2);
        reverse += datecorretc.charAt(3);
        
        txtFormattedFundacao.setText(reverse);
        txtNome.setText(time.getNome());
        txtPatrimonio.setText(time.getPatrimonio().toString());
        
        id=time.getId();
        oldName=time.getNome();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UiEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UiEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UiEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UiEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UiEdit(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnProcurarImg;
    private javax.swing.JLabel lbEscudo;
    private javax.swing.JLabel lbFundacao;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPatrimonio;
    private javax.swing.JTextField txtEscudo;
    private javax.swing.JFormattedTextField txtFormattedFundacao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPatrimonio;
    // End of variables declaration//GEN-END:variables
}
